from zoautil_py import mvscmd
from zoautil_py import datasets

from ztron.log import Log


def run(cmd:str='', DD_list:list=[], log:Log=None) -> dict:
    '''
    Run an mvs command.

    Params:
        command: The MVS command to execute
        DD_list: List of Data Definitions (DDs) to reference
    Returns:
        results: A dictionary of results from the job
    ''' 
    results = {}

    try:
        results = mvscmd.execute(pgm=cmd, dds=DD_list).to_dict()
    except Exception as e:
        log.error(f'Failed to run {cmd} command')
        log.error(f'{e.message}')
        log.error(f'{e.args}')

    cmd_show_results(results, DD_list, log)
    return results


def cmd_show_results(results:str={}, DD_list:list=[], log:Log=None)-> None:
    # Log all of the output generated by the ZOAU mvscmd utility.
    log.info('-------------------------')
    log.info('Results:')
    for k, v in results.items():
        log.info(f'    {k}: {v}')
    
    # Log all of the output generated by the command that we executed.
    for dd in DD_list:
        d = dd.get_mvscmd_string().split('"')
        if d[0] == '--SYSPRINT=':
            # There is a ',SHR' suffix on the spool dataset name to remove.
            spool_ds = d[1].split(',')[0]
            log.info(f'Spool dataset: {spool_ds}')
            job_output = datasets.read(spool_ds)

            for line in job_output.splitlines():
                log.info(f'>>> {line}')
            break
    log.info('-------------------------')

    return